# Generated by socfw

# Primary clocks
create_clock -name SYS_CLK -period 20.000 [get_ports {SYS_CLK}]

# Generated clocks
create_generated_clock -name clk_100mhz -multiply_by 2 -source [get_pins {clkpll|c0}] [get_pins {clkpll|c0}]
create_generated_clock -name clk_100mhz_sh -multiply_by 2 -source [get_pins {clkpll|c1}] [get_pins {clkpll|c1}]

# Derived uncertainty
derive_clock_uncertainty
