from __future__ import annotations

from pathlib import Path


def _pin(pin: str) -> str:
    """Return Quartus PIN_<x> location specifier, adding prefix if missing."""
    return pin if pin.startswith("PIN_") else f"PIN_{pin}"


class BoardTclEmitter:
    def emit(self, *, out_dir: str, system) -> str:
        hal_dir = Path(out_dir) / "hal"
        hal_dir.mkdir(parents=True, exist_ok=True)

        out = hal_dir / "board.tcl"
        lines: list[str] = []

        lines.append("# Generated by socfw")
        lines.append("")

        self._emit_device(lines, system.board)
        self._emit_system_pins(lines, system.board, system)
        self._emit_selected_resources(lines, system)

        out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        return str(out)

    def _emit_device(self, lines: list[str], board) -> None:
        if board.fpga_part:
            lines.append("# FPGA device")
            lines.append(f"set_global_assignment -name DEVICE {board.fpga_part}")
            lines.append("")

        if board.fpga_family:
            lines.append(f"set_global_assignment -name FAMILY \"{board.fpga_family}\"")
            lines.append("")

    def _emit_system_pins(self, lines: list[str], board, system=None) -> None:
        lines.append("# System pins")
        clk = board.sys_clock
        lines.append(f"set_location_assignment {_pin(clk.pin)} -to {clk.top_name}")
        if clk.io_standard:
            lines.append(f"set_instance_assignment -name IO_STANDARD \"{clk.io_standard}\" -to {clk.top_name}")

        rst = board.sys_reset
        if rst is not None and self._reset_is_used(system):
            lines.append(f"set_location_assignment {_pin(rst.pin)} -to {rst.top_name}")
            if rst.io_standard:
                lines.append(f"set_instance_assignment -name IO_STANDARD \"{rst.io_standard}\" -to {rst.top_name}")

        lines.append("")

    def _reset_is_used(self, system) -> bool:
        if system is None:
            return True
        for mod in system.project.modules:
            ip = system.ip_catalog.get(mod.type_name)
            if ip is not None and ip.reset.port:
                return True
        return False

    def _emit_selected_resources(self, lines: list[str], system) -> None:
        from socfw.board.feature_expansion import expand_features_for_project
        from socfw.board.pin_ownership import collect_pin_ownership

        board = system.board
        project = system.project
        selected = expand_features_for_project(board, project)

        # Add bind targets not already covered by a selected parent path
        for mod in project.modules:
            for pb in mod.port_bindings:
                if not pb.target.startswith("board:"):
                    continue
                path = pb.target[len("board:"):]
                if any(path == p or path.startswith(p + ".") for p in selected.paths):
                    continue
                selected.paths.append(path)

        if not selected.paths:
            return

        pin_uses = collect_pin_ownership(board, selected)
        if not pin_uses:
            return

        # Group by top_name to emit io_standard once per signal
        from collections import defaultdict
        top_to_uses: dict[str, list] = defaultdict(list)
        for use in pin_uses:
            top_to_uses[use.top_name].append(use)

        # Separate onboard from external for ordering
        onboard_tops: list[str] = []
        external_tops: list[str] = []
        for use in pin_uses:
            if use.resource_path.startswith("onboard."):
                if use.top_name not in onboard_tops:
                    onboard_tops.append(use.top_name)
            else:
                if use.top_name not in external_tops:
                    external_tops.append(use.top_name)

        board_overrides = getattr(getattr(system, "project", None), "board_overrides", {}) or {}

        if onboard_tops:
            lines.append("# Board resources")
            for top_name in sorted(onboard_tops):
                uses = top_to_uses[top_name]
                self._emit_pin_uses(lines, top_name, uses, board, board_overrides)
            lines.append("")

        if external_tops:
            lines.append("# External resources")
            for top_name in sorted(external_tops):
                uses = top_to_uses[top_name]
                self._emit_pin_uses(lines, top_name, uses, board, board_overrides)
            lines.append("")

    def _emit_pin_uses(self, lines: list[str], top_name: str, uses, board,
                       board_overrides: dict | None = None) -> None:
        from socfw.board.resource_tree import iter_resource_leaves

        scalar_uses = [u for u in uses if u.bit is None]
        vector_uses = [u for u in uses if u.bit is not None]

        if scalar_uses:
            u = scalar_uses[0]
            emit_cfg = self._get_emit_config(u, board, board_overrides)
            if emit_cfg.get("pin_assignment", True) is not False:
                lines.append(f"set_location_assignment {_pin(u.pin)} -to {top_name}")
            if emit_cfg.get("io_assignments", True) is not False:
                io_std = self._get_io_standard(u, board)
                if io_std:
                    lines.append(f"set_instance_assignment -name IO_STANDARD \"{io_std}\" -to {top_name}")
                cs = self._get_current_strength(u, board)
                if cs:
                    lines.append(f"set_instance_assignment -name CURRENT_STRENGTH_NEW \"{cs}\" -to {top_name}")
                sr = self._get_slew_rate(u, board)
                if sr is not None:
                    lines.append(f"set_instance_assignment -name SLEW_RATE {sr} -to {top_name}")
                if self._get_fast_input_register(u, board):
                    lines.append(f"set_instance_assignment -name FAST_INPUT_REGISTER ON -to {top_name}")
                if self._get_fast_output_register(u, board):
                    lines.append(f"set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to {top_name}")
                if self._get_global_clock(u, board):
                    lines.append(f"set_instance_assignment -name GLOBAL_SIGNAL GLOBAL_CLOCK -to {top_name}")

        if vector_uses:
            u0 = vector_uses[0]
            emit_cfg = self._get_emit_config(u0, board, board_overrides)
            if emit_cfg.get("pin_assignment", True) is not False:
                for u in sorted(vector_uses, key=lambda x: x.bit):
                    lines.append(f"set_location_assignment {_pin(u.pin)} -to {top_name}[{u.bit}]")
            if emit_cfg.get("io_assignments", True) is not False:
                io_std = self._get_io_standard(u0, board)
                if io_std:
                    lines.append(f"set_instance_assignment -name IO_STANDARD \"{io_std}\" -to {top_name}[*]")
                cs = self._get_current_strength(u0, board)
                if cs:
                    lines.append(f"set_instance_assignment -name CURRENT_STRENGTH_NEW \"{cs}\" -to {top_name}[*]")
                sr = self._get_slew_rate(u0, board)
                if sr is not None:
                    lines.append(f"set_instance_assignment -name SLEW_RATE {sr} -to {top_name}[*]")
                if self._get_fast_input_register(u0, board):
                    lines.append(f"set_instance_assignment -name FAST_INPUT_REGISTER ON -to {top_name}[*]")
                if self._get_fast_output_register(u0, board):
                    lines.append(f"set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to {top_name}[*]")
                if self._get_global_clock(u0, board):
                    lines.append(f"set_instance_assignment -name GLOBAL_SIGNAL GLOBAL_CLOCK -to {top_name}[*]")

    def _get_emit_config(self, use, board, board_overrides: dict | None) -> dict:
        """Merge emit config from board signal definition and project board_overrides."""
        sig = self._get_signal(use, board)
        sig_emit = dict(sig.emit) if sig is not None and hasattr(sig, "emit") else {}
        if board_overrides:
            specific_key = self._signal_board_ref(use, board)
            if specific_key:
                override = board_overrides.get(specific_key, {})
                override_emit = override.get("emit", {}) if isinstance(override, dict) else {}
                sig_emit.update(override_emit)
        return sig_emit

    def _signal_board_ref(self, use, board) -> str | None:
        """Return the board: ref for this signal (e.g. 'board:onboard.eth.rx_clk_0')."""
        path = use.resource_path
        if not path.startswith("onboard."):
            return None
        sub = path[len("onboard."):]
        res_key = sub.split(".")[0]
        res = board.onboard.get(res_key)
        if res is None:
            return None
        for sig_key, sig in res.scalars.items():
            if sig.top_name == use.top_name:
                return f"board:onboard.{res_key}.{sig_key}"
        for vec_key, vec in res.vectors.items():
            if vec.top_name == use.top_name:
                return f"board:onboard.{res_key}.{vec_key}"
        return None

    def _get_signal(self, use, board):
        """Return the BoardScalarSignal or BoardVectorSignal for a PinUse."""
        path = use.resource_path
        if path.startswith("onboard."):
            sub = path[len("onboard."):]
            res_key = sub.split(".")[0]
            res = board.onboard.get(res_key)
            if res is None:
                return None
            for sig in res.scalars.values():
                if sig.top_name == use.top_name:
                    return sig
            for vec in res.vectors.values():
                if vec.top_name == use.top_name:
                    return vec
        return None

    def _get_current_strength(self, use, board) -> str | None:
        sig = self._get_signal(use, board)
        return sig.current_strength if sig is not None else None

    def _get_slew_rate(self, use, board) -> int | None:
        sig = self._get_signal(use, board)
        return sig.slew_rate if sig is not None else None

    def _get_fast_input_register(self, use, board) -> bool:
        sig = self._get_signal(use, board)
        return sig.fast_input_register if sig is not None else False

    def _get_fast_output_register(self, use, board) -> bool:
        sig = self._get_signal(use, board)
        return sig.fast_output_register if sig is not None else False

    def _get_global_clock(self, use, board) -> bool:
        sig = self._get_signal(use, board)
        return sig.global_clock if sig is not None else False

    def _get_io_standard(self, use, board) -> str | None:
        path = use.resource_path
        if path.startswith("onboard."):
            sub = path[len("onboard."):]
            res_key = sub.split(".")[0]
            res = board.onboard.get(res_key)
            if res is None:
                return None
            for sig in res.scalars.values():
                if sig.top_name == use.top_name:
                    return sig.io_standard
            for vec in res.vectors.values():
                if vec.top_name == use.top_name:
                    return vec.io_standard
        elif path.startswith("external."):
            sub = path[len("external."):]
            external = board.resources.get("external") or {}
            parts = sub.split(".")
            cur = external
            for p in parts:
                if not isinstance(cur, dict) or p not in cur:
                    return None
                cur = cur[p]
            if isinstance(cur, dict):
                return cur.get("io_standard")
        return None
