from __future__ import annotations

from pathlib import Path


class BoardTclEmitter:
    def emit(self, *, out_dir: str, system) -> str:
        hal_dir = Path(out_dir) / "hal"
        hal_dir.mkdir(parents=True, exist_ok=True)

        out = hal_dir / "board.tcl"
        lines: list[str] = []

        lines.append("# Generated by socfw")
        lines.append("")

        self._emit_device(lines, system.board)
        self._emit_system_pins(lines, system.board)
        self._emit_selected_resources(lines, system)

        out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        return str(out)

    def _emit_device(self, lines: list[str], board) -> None:
        if board.fpga_part:
            lines.append("# FPGA device")
            lines.append(f"set_global_assignment -name DEVICE {board.fpga_part}")
            lines.append("")

        if board.fpga_family:
            lines.append("# FPGA family")
            lines.append(f"# family: {board.fpga_family}")
            lines.append("")

    def _emit_system_pins(self, lines: list[str], board) -> None:
        lines.append("# System pins")
        clk = board.sys_clock
        lines.append(f"set_location_assignment {clk.pin} -to {clk.top_name}")

        rst = board.sys_reset
        lines.append(f"set_location_assignment {rst.pin} -to {rst.top_name}")

        lines.append("")

    def _emit_selected_resources(self, lines: list[str], system) -> None:
        from socfw.board.feature_expansion import expand_features
        from socfw.board.pin_ownership import collect_pin_ownership

        board = system.board
        project = system.project

        profile = getattr(project, "feature_profile", None)
        use_refs = list(project.feature_refs or [])
        selected = expand_features(board, profile, use_refs)

        # Add bind targets not already covered
        for mod in project.modules:
            for pb in mod.port_bindings:
                if not pb.target.startswith("board:"):
                    continue
                path = pb.target[len("board:"):]
                if path not in selected.paths:
                    selected.paths.append(path)

        if not selected.paths:
            return

        pin_uses = collect_pin_ownership(board, selected)
        if not pin_uses:
            return

        # Group by top_name to emit io_standard once per signal
        from collections import defaultdict
        top_to_uses: dict[str, list] = defaultdict(list)
        for use in pin_uses:
            top_to_uses[use.top_name].append(use)

        # Separate onboard from external for ordering
        onboard_tops: list[str] = []
        external_tops: list[str] = []
        for use in pin_uses:
            if use.resource_path.startswith("onboard."):
                if use.top_name not in onboard_tops:
                    onboard_tops.append(use.top_name)
            else:
                if use.top_name not in external_tops:
                    external_tops.append(use.top_name)

        if onboard_tops:
            lines.append("# Board resources")
            for top_name in sorted(onboard_tops):
                uses = top_to_uses[top_name]
                self._emit_pin_uses(lines, top_name, uses, board)
            lines.append("")

        if external_tops:
            lines.append("# External resources")
            for top_name in sorted(external_tops):
                uses = top_to_uses[top_name]
                self._emit_pin_uses(lines, top_name, uses, board)
            lines.append("")

    def _emit_pin_uses(self, lines: list[str], top_name: str, uses, board) -> None:
        from socfw.board.resource_tree import iter_resource_leaves

        scalar_uses = [u for u in uses if u.bit is None]
        vector_uses = [u for u in uses if u.bit is not None]

        if scalar_uses:
            u = scalar_uses[0]
            lines.append(f"set_location_assignment {u.pin} -to {top_name}")
            io_std = self._get_io_standard(u, board)
            if io_std:
                lines.append(f"set_instance_assignment -name IO_STANDARD \"{io_std}\" -to {top_name}")

        if vector_uses:
            for u in sorted(vector_uses, key=lambda x: x.bit):
                lines.append(f"set_location_assignment {u.pin} -to {top_name}[{u.bit}]")
            io_std = self._get_io_standard(vector_uses[0], board)
            if io_std:
                lines.append(f"set_instance_assignment -name IO_STANDARD \"{io_std}\" -to {top_name}")

    def _get_io_standard(self, use, board) -> str | None:
        path = use.resource_path
        if path.startswith("onboard."):
            sub = path[len("onboard."):]
            res_key = sub.split(".")[0]
            res = board.onboard.get(res_key)
            if res is None:
                return None
            for sig in res.scalars.values():
                if sig.top_name == use.top_name:
                    return sig.io_standard
            for vec in res.vectors.values():
                if vec.top_name == use.top_name:
                    return vec.io_standard
        elif path.startswith("external."):
            sub = path[len("external."):]
            external = board.resources.get("external") or {}
            parts = sub.split(".")
            cur = external
            for p in parts:
                if not isinstance(cur, dict) or p not in cur:
                    return None
                cur = cur[p]
            if isinstance(cur, dict):
                return cur.get("io_standard")
        return None
