from __future__ import annotations

from pathlib import Path


class BoardTclEmitter:
    def emit(self, *, out_dir: str, system) -> str:
        hal_dir = Path(out_dir) / "hal"
        hal_dir.mkdir(parents=True, exist_ok=True)

        out = hal_dir / "board.tcl"
        lines: list[str] = []

        lines.append("# Generated by socfw")
        lines.append("")

        self._emit_device(lines, system.board)
        self._emit_system_pins(lines, system.board)
        self._emit_resources(lines, system.board)

        out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        return str(out)

    def _emit_device(self, lines: list[str], board) -> None:
        if board.fpga_part:
            lines.append("# FPGA device")
            lines.append(f"set_global_assignment -name DEVICE {board.fpga_part}")
            lines.append("")

        if board.fpga_family:
            lines.append("# FPGA family")
            lines.append(f"# family: {board.fpga_family}")
            lines.append("")

    def _emit_system_pins(self, lines: list[str], board) -> None:
        lines.append("# System pins")
        clk = board.sys_clock
        lines.append(f"set_location_assignment {clk.pin} -to {clk.top_name}")

        rst = board.sys_reset
        lines.append(f"set_location_assignment {rst.pin} -to {rst.top_name}")

        lines.append("")

    def _emit_resources(self, lines: list[str], board) -> None:
        if not board.onboard:
            return

        lines.append("# Board resources")
        for _, resource in sorted(board.onboard.items()):
            for sig in sorted(resource.scalars.values(), key=lambda s: s.top_name):
                lines.append(f"set_location_assignment {sig.pin} -to {sig.top_name}")

            for vec in sorted(resource.vectors.values(), key=lambda v: v.top_name):
                for idx in sorted(vec.pins):
                    lines.append(
                        f"set_location_assignment {vec.pins[idx]} -to {vec.top_name}[{idx}]"
                    )

        lines.append("")
