from __future__ import annotations

from pathlib import Path

from socfw.build.context import BuildContext
from socfw.build.manifest import GeneratedArtifact
from socfw.build.vendor_artifacts import collect_vendor_artifacts
from socfw.ir.files import FilesIR
from socfw.ir.rtl import RtlModuleIR


def _assignment_for(path: str) -> str | None:
    lower = path.lower()
    if lower.endswith(".qip"):
        return f'set_global_assignment -name QIP_FILE "{path}"'
    if lower.endswith(".sdc"):
        return f'set_global_assignment -name SDC_FILE "{path}"'
    if lower.endswith(".sv"):
        return f'set_global_assignment -name SYSTEMVERILOG_FILE "{path}"'
    if lower.endswith(".v"):
        return f'set_global_assignment -name VERILOG_FILE "{path}"'
    return None


class FilesTclEmitter:
    def emit(self, *, out_dir: str, system, planned_bridges: list, project_dir: str | None = None) -> str:
        hal_dir = Path(out_dir) / "hal"
        hal_dir.mkdir(parents=True, exist_ok=True)

        base = Path(project_dir).resolve() if project_dir else Path.cwd().resolve()
        cwd = Path.cwd().resolve()

        def _norm(p: str) -> str:
            abs_p = Path(p).resolve()
            try:
                return str(abs_p.relative_to(base))
            except ValueError:
                pass
            try:
                return str(abs_p.relative_to(cwd))
            except ValueError:
                return str(abs_p)

        out = hal_dir / "files.tcl"
        lines: list[str] = []

        lines.append("# Generated by socfw")
        lines.append("")

        for fp in self._collect_all_files(system, planned_bridges):
            assignment = _assignment_for(_norm(fp))
            if assignment:
                lines.append(assignment)

        out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        return str(out)

    def _collect_all_files(self, system, planned_bridges: list) -> list[str]:
        files: list[str] = []

        used_types = {m.type_name for m in system.project.modules}
        for type_name in sorted(used_types):
            ip = system.ip_catalog.get(type_name)
            if ip is None:
                continue
            for fp in getattr(ip.artifacts, "synthesis", ()):
                files.append(str(fp))
            if ip.vendor_info is not None:
                for sdc in ip.vendor_info.sdc:
                    files.append(str(sdc))

        for bridge in planned_bridges:
            files.append(str(bridge.rtl_file))

        return sorted(dict.fromkeys(files))


class QuartusFilesEmitter:
    family = "files"

    def emit(self, ctx: BuildContext, ir: RtlModuleIR | FilesIR) -> list[GeneratedArtifact]:
        out = Path(ctx.out_dir) / "files.tcl"
        out.parent.mkdir(parents=True, exist_ok=True)
        cwd = Path.cwd().resolve()

        def _norm(p: str) -> str:
            try:
                return str(Path(p).resolve().relative_to(cwd))
            except ValueError:
                return p

        lines: list[str] = []
        lines.append("# AUTO-GENERATED - DO NOT EDIT")
        lines.append("set_global_assignment -name SYSTEMVERILOG_FILE rtl/soc_top.sv")

        if isinstance(ir, FilesIR):
            for q in ir.qip_files:
                lines.append(f"set_global_assignment -name QIP_FILE {_norm(q)}")
            for fp in ir.rtl_files:
                lines.append(self._file_assignment(_norm(fp)))
            for s in ir.sdc_files:
                lines.append(f"set_global_assignment -name SDC_FILE {_norm(s)}")
        else:
            for fp in sorted(ir.extra_sources):
                lines.append(self._file_assignment(_norm(fp)))

        out.write_text("\n".join(lines) + "\n", encoding="ascii")

        return [
            GeneratedArtifact(
                family=self.family,
                path=str(out),
                generator=self.__class__.__name__,
            )
        ]

    @staticmethod
    def _file_assignment(fp: str) -> str:
        if fp.endswith(".qip"):
            return f"set_global_assignment -name QIP_FILE {fp}"
        if fp.endswith(".sdc"):
            return f"set_global_assignment -name SDC_FILE {fp}"
        if fp.endswith(".v"):
            return f"set_global_assignment -name VERILOG_FILE {fp}"
        if fp.endswith(".vhd") or fp.endswith(".vhdl"):
            return f"set_global_assignment -name VHDL_FILE {fp}"
        return f"set_global_assignment -name SYSTEMVERILOG_FILE {fp}"
