from __future__ import annotations

from pathlib import Path


class SdcEmitter:
    def emit(self, *, out_dir: str, system) -> str:
        timing_dir = Path(out_dir) / "timing"
        timing_dir.mkdir(parents=True, exist_ok=True)

        out = timing_dir / "soc_top.sdc"
        lines: list[str] = []

        lines.append("# Generated by socfw")
        lines.append("")

        self._emit_primary_clock(lines, system)
        self._emit_generated_clocks(lines, system)
        self._emit_derive_uncertainty(lines, system)
        self._emit_io_delays(lines, system)
        self._emit_io_overrides(lines, system)
        self._emit_false_paths(lines, system)

        out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        return str(out)

    def _emit_primary_clock(self, lines: list[str], system) -> None:
        clk = system.board.sys_clock
        period_ns = 1_000_000_000.0 / float(clk.frequency_hz)

        lines.append("# Primary clocks")
        lines.append(
            f"create_clock -name {clk.top_name} "
            f"-period {period_ns:.3f} [get_ports {{{clk.top_name}}}]"
        )
        lines.append("")

    def _emit_generated_clocks(self, lines: list[str], system) -> None:
        timing = system.timing
        if timing is None or not timing.generated_clocks:
            return

        lines.append("# Generated clocks")
        for g in sorted(timing.generated_clocks, key=lambda x: x.name):
            args = []
            if g.divide_by is not None and g.divide_by != 1:
                args.append(f"-divide_by {g.divide_by}")
            if g.multiply_by is not None and g.multiply_by != 1:
                args.append(f"-multiply_by {g.multiply_by}")

            arg_text = (" " + " ".join(args)) if args else ""
            src_pin = self._pll_input_pin(g.source_instance)
            tgt_pin = self._pll_output_pin(g.source_instance, g.source_clock)
            lines.append(
                f"create_generated_clock -name {g.name}{arg_text} "
                f"-source [get_pins {{{src_pin}}}] "
                f"[get_pins {{{tgt_pin}}}]"
            )
        lines.append("")

    def _pll_input_pin(self, instance: str) -> str:
        return f"{instance}|inclk[0]"

    def _pll_output_pin(self, instance: str, output: str) -> str:
        if len(output) >= 2 and output[0] == "c" and output[1:].isdigit():
            idx = int(output[1:])
            return f"{instance}|altpll_component|auto_generated|pll1|clk[{idx}]"
        return f"{instance}|{output}"

    def _emit_derive_uncertainty(self, lines: list[str], system) -> None:
        timing = system.timing
        if timing is None or not timing.derive_uncertainty:
            return
        lines.append("# Derived uncertainty")
        lines.append("derive_clock_uncertainty")
        lines.append("")

    def _resolve_sdc_clock(self, name: str, system) -> str:
        """Resolve a timing domain name to its SDC clock name (board port name)."""
        timing = system.timing
        if timing:
            for pc in timing.primary_clocks:
                if pc.name == name:
                    return pc.source_port
        return name

    def _emit_io_delays(self, lines: list[str], system) -> None:
        timing = system.timing
        if timing is None or not timing.io_auto:
            return

        clock = self._resolve_sdc_clock(
            timing.io_default_clock or system.board.sys_clock.top_name,
            system,
        )
        input_max = timing.io_default_input_max_ns
        input_min = timing.io_default_input_min_ns if timing.io_default_input_min_ns is not None else input_max
        output_max = timing.io_default_output_max_ns
        output_min = timing.io_default_output_min_ns if timing.io_default_output_min_ns is not None else output_max

        if input_max is None and output_max is None:
            return

        clk_name = system.board.sys_clock.top_name
        rst_name = system.board.sys_reset.top_name if system.board.sys_reset else None
        exclude = f"{{{clk_name}}}" if rst_name is None else f"{{{clk_name} {rst_name}}}"
        data_inputs = f"[remove_from_collection [all_inputs] [get_ports {exclude}]]"

        lines.append("# Default IO delays")

        if input_max is not None:
            lines.append(
                f"set_input_delay -clock {clock} "
                f"-max {float(input_max):.3f} {data_inputs}"
            )
            lines.append(
                f"set_input_delay -clock {clock} "
                f"-min {float(input_min):.3f} {data_inputs}"
            )

        if output_max is not None:
            lines.append(
                f"set_output_delay -clock {clock} "
                f"-max {float(output_max):.3f} [all_outputs]"
            )
            lines.append(
                f"set_output_delay -clock {clock} "
                f"-min {float(output_min):.3f} [all_outputs]"
            )

        lines.append("")

    def _emit_io_overrides(self, lines: list[str], system) -> None:
        timing = system.timing
        if timing is None or not timing.io_overrides:
            return

        lines.append("# IO delay overrides")
        for ov in timing.io_overrides:
            clock = self._resolve_sdc_clock(ov.clock, system)
            if ov.comment:
                lines.append(f"# {ov.comment}")
            port_expr = f"[get_ports {{{ov.port}}}]"
            min_ns = ov.min_ns if ov.min_ns is not None else ov.max_ns
            if ov.direction == "input":
                lines.append(f"set_input_delay -clock {clock} -max {float(ov.max_ns):.3f} {port_expr}")
                lines.append(f"set_input_delay -clock {clock} -min {float(min_ns):.3f} {port_expr}")
            else:
                lines.append(f"set_output_delay -clock {clock} -max {float(ov.max_ns):.3f} {port_expr}")
                lines.append(f"set_output_delay -clock {clock} -min {float(min_ns):.3f} {port_expr}")
        lines.append("")

    def _emit_false_paths(self, lines: list[str], system) -> None:
        timing = system.timing
        if timing is None or not timing.false_paths:
            return

        lines.append("# False paths")
        for fp in timing.false_paths:
            if fp.comment:
                lines.append(f"# {fp.comment}")
            if fp.from_clock and fp.to_clock:
                lines.append(
                    f"set_false_path -from [get_clocks {{{fp.from_clock}}}] "
                    f"-to [get_clocks {{{fp.to_clock}}}]"
                )
            elif fp.from_clock:
                lines.append(f"set_false_path -from [get_clocks {{{fp.from_clock}}}]")
            elif fp.to_clock:
                lines.append(f"set_false_path -to [get_clocks {{{fp.to_clock}}}]")
            elif fp.from_port:
                lines.append(f"set_false_path -from [get_ports {{{fp.from_port}}}]")

        lines.append("")
