# Generated by socfw

# FPGA device
set_global_assignment -name DEVICE EP4CE55F23C8

# FPGA family
# family: Cyclone IV E

# System pins
set_location_assignment T2 -to SYS_CLK
set_location_assignment W13 -to RESET_N

# Board resources
set_location_assignment E4 -to ONB_LEDS[0]
set_location_assignment A8 -to ONB_LEDS[1]
set_location_assignment B8 -to ONB_LEDS[2]
set_location_assignment A7 -to ONB_LEDS[3]
set_location_assignment B7 -to ONB_LEDS[4]
set_location_assignment A6 -to ONB_LEDS[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to ONB_LEDS

# External resources
set_location_assignment T6 -to ZS_ADDR[0]
set_location_assignment R6 -to ZS_ADDR[1]
set_location_assignment R5 -to ZS_ADDR[2]
set_location_assignment P5 -to ZS_ADDR[3]
set_location_assignment P6 -to ZS_ADDR[4]
set_location_assignment V7 -to ZS_ADDR[5]
set_location_assignment V6 -to ZS_ADDR[6]
set_location_assignment U7 -to ZS_ADDR[7]
set_location_assignment U6 -to ZS_ADDR[8]
set_location_assignment N6 -to ZS_ADDR[9]
set_location_assignment N8 -to ZS_ADDR[10]
set_location_assignment P7 -to ZS_ADDR[11]
set_location_assignment P8 -to ZS_ADDR[12]
set_location_assignment N9 -to ZS_BA[0]
set_location_assignment P9 -to ZS_BA[1]
set_location_assignment U1 -to ZS_CAS_N
set_location_assignment V3 -to ZS_CKE
set_location_assignment V4 -to ZS_CLK
set_location_assignment V2 -to ZS_CS_N
set_location_assignment T10 -to ZS_DQ[0]
set_location_assignment T9 -to ZS_DQ[1]
set_location_assignment V10 -to ZS_DQ[2]
set_location_assignment V9 -to ZS_DQ[3]
set_location_assignment U9 -to ZS_DQ[4]
set_location_assignment U8 -to ZS_DQ[5]
set_location_assignment T8 -to ZS_DQ[6]
set_location_assignment T7 -to ZS_DQ[7]
set_location_assignment P3 -to ZS_DQ[8]
set_location_assignment P4 -to ZS_DQ[9]
set_location_assignment R2 -to ZS_DQ[10]
set_location_assignment R1 -to ZS_DQ[11]
set_location_assignment R4 -to ZS_DQ[12]
set_location_assignment R3 -to ZS_DQ[13]
set_location_assignment T5 -to ZS_DQ[14]
set_location_assignment T4 -to ZS_DQ[15]
set_location_assignment V11 -to ZS_DQM[0]
set_location_assignment R0 -to ZS_DQM[1]
set_location_assignment U2 -to ZS_RAS_N
set_location_assignment V1 -to ZS_WE_N
