# Generated by socfw

set_global_assignment -name QIP_FILE "packs/vendor-intel/ip/sdram_ctrl/files/sdram_ctrl.qip"
set_global_assignment -name SDC_FILE "packs/vendor-intel/ip/sdram_ctrl/files/sdram_ctrl.sdc"
set_global_assignment -name VERILOG_FILE "packs/vendor-intel/ip/sdram_ctrl/files/sdram_ctrl.v"
set_global_assignment -name SYSTEMVERILOG_FILE "socfw/bridges/simple_bus_to_wishbone_bridge.sv"
