# Generated by socfw

set_global_assignment -name VERILOG_FILE packs/vendor-intel/ip/sdram_ctrl/files/sdram_ctrl.v
set_global_assignment -name VERILOG_FILE socfw/bridges/simple_bus_to_wishbone_bridge.sv

# Vendor QIP files
set_global_assignment -name QIP_FILE packs/vendor-intel/ip/sdram_ctrl/files/sdram_ctrl.qip

# Vendor SDC files
set_global_assignment -name SDC_FILE packs/vendor-intel/ip/sdram_ctrl/files/sdram_ctrl.sdc
