# Generated by socfw

set_global_assignment -name QIP_FILE "packs/vendor-intel/ip/sys_pll/files/sys_pll.qip"
set_global_assignment -name SDC_FILE "packs/vendor-intel/ip/sys_pll/files/sys_pll.sdc"
set_global_assignment -name VERILOG_FILE "packs/vendor-intel/ip/sys_pll/files/sys_pll.v"
set_global_assignment -name SYSTEMVERILOG_FILE "ip/blink_test.sv"
