version: 2
kind: project

project:
  name: ac608_blink
  mode: standalone
  board: ac608_ep4ce15
  board_file: boards/ac608_ep4ce15.yaml
  output_dir: build/gen

registries:
  packs:
    - ../../packs/builtin
  ip:
    - ip

features:
  use:
    - board:onboard.leds

timing:
  file: timing.yaml

clocks:
  primary:
    domain: sys_clk
    source: board:SYS_CLK
    frequency_hz: 50000000
  generated: []

modules:
  - instance: blink0
    type: blink_test
    clocks:
      SYS_CLK: sys_clk
    params:
      CLK_FREQ: 50000000
    bind:
      ports:
        ONB_LEDS:
          target: board:onboard.leds

artifacts:
  emit: [rtl, board, timing]
