from pathlib import Path

from socfw.emit.board_tcl_emitter import BoardTclEmitter
from socfw.model.board import BoardClockDef, BoardResetDef, BoardModel, BoardResource, BoardVectorSignal
from socfw.model.enums import PortDir
from socfw.model.project import ProjectModel
from socfw.model.system import SystemModel


def _make_system() -> SystemModel:
    board = BoardModel(
        board_id="demo",
        vendor=None,
        title=None,
        fpga_family="Cyclone IV E",
        fpga_part="EP4CE55F23C8",
        sys_clock=BoardClockDef(
            id="sys_clk",
            top_name="SYS_CLK",
            pin="PIN_A1",
            frequency_hz=50_000_000,
        ),
        sys_reset=BoardResetDef(
            id="reset_n",
            top_name="RESET_N",
            pin="PIN_B1",
            active_low=True,
        ),
        onboard={
            "leds": BoardResource(
                key="leds",
                kind="generic",
                vectors={
                    "default": BoardVectorSignal(
                        key="default",
                        top_name="ONB_LEDS",
                        direction=PortDir.OUTPUT,
                        width=2,
                        pins={0: "PIN_C1", 1: "PIN_C2"},
                    )
                },
            )
        },
    )
    project = ProjectModel(name="demo", mode="standalone", board_ref="demo", feature_refs=["board:onboard.leds"])
    return SystemModel(board=board, project=project, timing=None, ip_catalog={})


def test_board_tcl_emitter_writes_clock_reset_and_leds(tmp_path):
    system = _make_system()
    out = BoardTclEmitter().emit(out_dir=str(tmp_path), system=system)
    text = Path(out).read_text(encoding="utf-8")

    assert "set_global_assignment -name DEVICE EP4CE55F23C8" in text
    assert "set_location_assignment PIN_A1 -to SYS_CLK" in text
    assert "set_location_assignment PIN_B1 -to RESET_N" in text
    assert "set_location_assignment PIN_C1 -to ONB_LEDS[0]" in text
    assert "Generated by socfw" in text
